# Project
version=1.0.4
group=com.finndog.moogs_paths
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Moog's Paths
mod_author=finndog
mod_id=moogs_paths
license=CC0-1.0
credits=FinnDog
description=Adds a generated network of paths and trails to the overworld, with biome-specific styles and roadside decorations like cairns, signposts and lamps. Fully configurable through datapacks.
minecraft_version_range=[1.20.1]

# Links
mod_homepage=https://github.com/FinnSetchell/MoogsPaths
mod_issues=https://github.com/FinnSetchell/MoogsPaths/issues
mod_discord=https://discord.gg/S5nffJbuvA
mod_kofi=https://ko-fi.com/finndog
mod_curseforge=https://legacy.curseforge.com/minecraft/mc-mods/mp-moogs-paths
mod_modrinth=https://modrinth.com/project/mp-moogs-paths
mod_releases=https://github.com/FinnSetchell/MoogsPaths/releases

# Publishing
cf_project_id=1546855
modrinth_project_id=HDB8pnki
publish_mc_start=1.20.1
publish_mc_end=1.20.1
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Discord webhook settings
discord_ping=false
discord_role_id=1466012771379581039
discord_avatar_url=https://media.forgecdn.net/avatars/thumbnails/1814/575/64/64/639147005829648185.png
discord_banner_url=https://pub-24a4e0e7ea8544a5b6f73c3a23512589.r2.dev/images/d5e8c0f59add420ea9e76f95544c256a.png
discord_embed_color=#8B6914

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
